#Embedded file name: toontown.speedchat.TTSCDecoders
from toontown.speedchat.TTSCToontaskTerminal import decodeTTSCToontaskMsg
from toontown.speedchat.TTSCResistanceTerminal import decodeTTSCResistanceMsg
