#Embedded file name: toontown.settings.ToontownSettings
DefaultSettings = {'fullscreen': False,
 'music': True,
 'sfx': True,
 'musicVol': 1.0,
 'sfxVol': 1.0,
 'loadDisplay': 'pandagl',
 'toonChatSounds': True,
 'newGui': False,
 'show-disclaimer': True,
 'fieldofview': 52,
 'show-cog-levels': True,
 'health-meter-mode': 2,
 'experienceBarMode': True,
 'smoothanimations': True,
 'tpmsgs': True,
 'friendstatusmsgs': True,
 'doorkey': True,
 'interactkey': True,
 'experimental-touch': False,
 'anisotropic-filtering': 0,
 'anti-aliasing': False,
 'vertical-sync': False,
 'language': 'English',
 'aspect-ratio': 0,
 'streamerMode': False,
 'lastNametag': {},
 'lastEffect': {},
 'lastRod': {},
 'keymap': {},
 'acceptingNewFriends': {},
 'acceptingNonFriendWhispers': {},
 'want-Custom-Controls': False}
AnistrophicOptions = [0,
 2,
 4,
 8,
 16]
AspectRatios = [0,
 1.33333,
 1.25,
 1.77777,
 2.33333]
AspectRatioLabels = ['Adaptive',
 '4:3',
 '5:3',
 '16:9',
 '21:9']
resolution_table = [(800, 600),
 (1024, 768),
 (1280, 1024),
 (1600, 1200),
 (1280, 720),
 (1920, 1080)]
